development:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  database: school_management
  pool: 5


# Employee.update_all(encrypted_password: BCrypt::Password.create("11111111"))